// cotizador-prestamos-vue/src/components/Button.vue
<script setup>

const props = defineProps(['operador', 'fn'])
</script>

<template>
    <button type="button" class="h-10 w-10 flex items-center justify-center font-bold bg-lime-500 rounded-full 
        hover:outline-none hover:ring-2 hover:ring-offset-2 hover:ring-lime-500 text-white text-2xl" @click="fn">{{
        operador }}</button>

</template>

// cotizador-prestamos-react/src/components/Button.jsx

export default function Button({ operador, fn }) {
    return (
        <button className="w-10 h-10 flex items-center justify-center font-black text-white text-2xl 
        bg-lime-500 rounded-full hover:outline-none hover:ring-2 hover:ring-offset-2 hover:bg-lime-500 "
            onClick={fn}
        >
            {operador}
        </button>
    )
}
